[tool.poetry]
package-mode = true
name = "CeDNe"
version = "0.1.0"
description = "CeDNe (s'Idni) is a library for integrating various omic level datasets together into a graph format."
authors = ["Sahil Moza <sahil.moza@gmail.com>"]
maintainers = ["Sahil Moza <sahil.moza@gmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://cedne.org"
repository = "https://github.com/sahilm89/cedne"

[tool.poetry.dependencies]
python = "^3.12"
networkx = "^3.3"
matplotlib = "^3.9.0"
numpy = "^1.26.4"
scipy = "^1.13.1"
openpyxl = "^3.1.3"
pandas = "2.0.3"
ipykernel = "^6.29.4"
textalloc = "^1.0.5"
pytest = "^8.2.2"
sphinx = "^7.3.7"
sphinx-rtd-theme = "^2.0.0"
pydata-sphinx-theme = "^0.15.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
